# Copyright (c) 2010 David Nies
# http://www.twitter.com/Sh4pe
#  
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#   
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#    
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# this works, but it is not nice at all yet... :/

# always supply env!
allTests = []
def testRunner(env, name):
	curDir = './src/'
	allTests.append('run'+name)
	env.AlwaysBuild(env.Alias('run'+name, [], curDir+name))

# debug?
debug = ARGUMENTS.get('debug', 'yes')
cxxflags = ''
if debug == 'yes':
	cxxflags = '-ggdb'
	
env = Environment(CPPPATH='.', CXXFLAGS=cxxflags)
env.ParseConfig("gtest-config --ldflags --libs")

env.Program('sudokusolver', Split('main.cc SudokuSolver.cc'))
env.Program('testBoard', Split('testBoard.cc SudokuSolver.cc'))

# test runners
testRunner(env, 'testBoard')

# all tests
env.AlwaysBuild(env.Alias('tests', allTests, []))
